# # EM DESENVOLVIMENTO! Objetivo: atualizar o scrap todos os dias.
#
# on:
#   schedule:
#     - cron: '0 14 * * *'
#
# name: update data
#
# jobs:
#   update:
#     name: update data
#     runs-on: macOS-latest
#     timeout-minutes: 20
#   steps:
#       - uses: actions/checkout@v1
#       - uses: r-lib/actions/setup-r@v1
#       - uses: r-lib/actions/setup-pandoc@v1
#       - name: Install packages dependencies
#         run: |
#           install.packages("remotes")
#           remotes::install_local(".")
#           remotes::install_cran("readr")
#           remotes::install_cran("glue")
#           remotes::install_cran("usethis")
#           remotes::install_cran("dplyr")
#           remotes::install_cran("magritrr")
#           remotes::install_cran("janitor")
#           remotes::install_cran("tibble")
#           remotes::install_cran("purrr")
#           remotes::install_cran("jsonlite")
#           remotes::install_cran("httr")
#       - name: <namestep2>
#         run: |
#         Rscript -e 'rmarkdown::render("examples/README.Rmd")' # mudar isso, executar outro c√≥digo
#       - name: <namestep3>
#         run: |
#           git commit <some file>.md -m 'Re-build <file>.Rmd' || echo "No changes to commit"
#           git push https://${{github.actor}}:${{secrets.GH_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
